### ISSUE TITLE
[BazQux Reader] Return wrong challenge

### ISSUE THREAD

**Issue by marienfressinaud** [flusio/Webubbub#1]
The hub cannot verify BazQux Reader subscriptions because it always returns `Are you hub???` when we try to verify its intent.

See [crawler.bazqux.com/pshb_ping](https://crawler.bazqux.com/pshb_ping), it behaves the same with a valid payload.

**Comment by da2x** [comment]
BazQux requires that you store and echo the `hub.verify_token` in the subscription request. It was part of PubSubHubbub up to version 0.3, but deprecated in 0.4 and the WebSub rebrand.

**Comment by marienfressinaud** [comment]
It looks like the subscriptions from BazQux are now verified so I would say they fixed it on their side.
