### ISSUE TITLE
[Feedly] Return 404 error code on verification

### ISSUE THREAD

**Issue by marienfressinaud** [flusio/Webubbub#2]
The hub cannot verify Feedly subscriptions because it always returns a 404 error when we try to verify its intent.

The error is "detailed" in the body:

```json
{
    "errorCode": 404,
    "errorId": "ap11int-sv2.2019123100.3210897"
}
```

which is quite obscure…

Actually my guess is that it's related to the way we generate the intent URL: [I forgot to `urlencode` the topic](https://github.com/flusio/Webubbub/blob/master/src/models/Subscription.php#L177).
I'll check my guess before submitting a fix.

**Comment by da2x** [comment]
Verify that the following components are urlencoded.  You run the callback through urldecode, so these might get messed up.

    http://push.feedly.com/v3/push/<urlencode>?hubUrl=<urlencode>&hub.mode=subscribe…

**Comment by marienfressinaud** [comment]
I can confirm Feedly subscriptions are now verified, thanks!
